Подготовил код для генерации данных по шаблону
htmlacademy-javascript/1801005-keksobooking-26 pull request #4
Opened 2022-08-10 00:27 UTC by Mangustttinio

2022-08-10 08:20 UTC, o-bender requested changes

2022-08-10 08:20 UTC, o-bender commented on js/create-data/create-card.js
> +const getLodgingType = (lodging) => {
Да, так работать будет, но читать такую конструкцию сложно. Куда проще использовать:
```
const housingTypes = {
    hotel: 'Отель',
    house: 'Дом',
    и т.д.
}
```

2022-08-10 08:20 UTC, o-bender commented on js/create-data/create-card.js
> +    cardNode.querySelector('.popup__features').textContent = ads.offer.features;
Увы, но нет. ads.offer.features это список фичей. И если мы его поместим в dom элемент, то получим вместо иконок просто список слов через запятую.

2022-08-10 08:20 UTC, o-bender commented on js/create-data/create-card.js
> +    cardNode.querySelector('.popup__description').textContent = ads.offer.description;
Как думаешь, что мы увидим на экране если description будет отсутствовать в ads.offer?

2022-08-10 08:20 UTC, o-bender commented on js/create-data/create-card.js
> +    cardNode.querySelector('.popup__photo').textContent = ads.offer.photos;
Тоже самое что и с features.

2022-08-10 08:20 UTC, o-bender commented on js/create-data/create-card.js
> +    cardNode.querySelector('.popup__text--capacity').textContent = `Заезд после ${ads.offer.checkin} , выезд до ${ads.offer.checkout}`;
Лишний пробел перед запятой.

2022-08-10 08:20 UTC, o-bender commented on js/create-data/create-card.js
> +const getPopup = () => {
1. Сейчас функция ничего не возвращает, на оборот сейчас она сразу что-то помещает в разметку. Правильней использовать слово render.
2. Эта функция как раз должна бы возвращать один созданный элемент popup. Т.к. по заданию надо нарисовать одну карточку отеля.

2022-08-10 08:20 UTC, o-bender commented on js/create-data/create-card.js
> +const addingArray = generateAds();
Как я вчера упоминал на консультации программа должна начинаться и завершаться в main.js. А такой вызов это сайд-эффект. Его необходимо производить в main.js.

2022-08-10 17:21 UTC, o-bender requested changes

2022-08-10 17:21 UTC, o-bender commented on js/create-data/create-card.js
> +const renderPopup = (array) => {
Я тут про другое чуток:) Эта функция будет вызываться при нажатии на маркер на карте. Т.е. нажал на маркер, эта функция нарисовала и вернула dom разметку и затем эта разметка вставится в popup. Т.е. не будет необходимости рисовать сразу много card элементов.
Так что давай так:
1. принимать функция должна 1 элемент ads
2. возвращать должна cardNode
Для того что бы поместить cardNode на карту напиши ещё одну функцию что-то вроде:
```
const insertCardToMap = (card) => mapCanvas.appendChild(card);
```
и всё это дело вызывай в main. примерно так:
```
insertCardToMap(renderPopup(generateAds(1)));
```

2022-08-10 17:21 UTC, o-bender commented on js/create-data/create-card.js
> +    const newAds = ads;
а это зачем?

2022-08-10 17:21 UTC, o-bender commented on js/create-data/create-card.js
> +    featuresArray.forEach((element) => {
1. обрати внимание, что функция renderPopup уже прямо таки огромная.
2. вот эту генерацию features `featuresArray.forEach((element) => {` стоит вынести в отдельную функцию `const renderFeatures = (features) => `. И эта функция будет возвращать фрагмент или массив li-шек.
3. Как забыть о createDocumentFragment. Напишу синтетический пример:
```
const domElements = [1,2,3,4,5].map((value) => {
    const element = document.createElement('li');
    element.textContent = value;
    return element;
});
const ulElement = document.createElement('ul');
ulElement.append(...domElements)
```

2022-08-10 17:21 UTC, o-bender commented on js/create-data/create-card.js
> +    const pDescription = document.createElement('p');
Не понял смысл махинаций:) вопрос в том что будет если `newAds.offer.description === undefined` или `cardNode.querySelector('.popup__description') === undefined`?
В первом случае скорей всего ничего. Максимум увидишь слово undefined в разметке. И то вроде такое поведение уже не встретишь в браузерах.
А во втором точно получишь ошибку, что пытаешься обратиться к textContent. А у undefined такого свойства нет.

2022-08-10 17:35 UTC, Mangustttinio commented on js/create-data/create-card.js
> +    const newAds = ads;
19 строка - делаю пустым место для вставки 
20 строка - ввожу константу для более простой записи добавления тега 
21 строка - написал её, так как почему-то у меня не работало простое вписывание ads

2022-08-10 18:26 UTC, Mangustttinio commented on js/create-data/create-card.js
> +const renderPopup = (array) => {
TypeError: Argument 1 ('node') to Node.appendChild must be an instance of Node 
Выдало эту ошибку

2022-08-10 20:33 UTC, Mangustttinio commented on js/create-data/create-card.js
> +    featuresArray.forEach((element) => {
вынес функцию

2022-08-10 20:56 UTC, Mangustttinio commented on js/create-data/create-card.js
> +    featuresArray.forEach((element) => {
вы предлагаете полностью убрать шаблон и эту конструкцию?

2022-08-10 21:16 UTC, Mangustttinio commented on js/create-data/create-card.js
> +    const pDescription = document.createElement('p');
Извините, что вы мне пытаетесь донести, а я до сих пор не сдвигаюсь

2022-08-10 22:29 UTC, Mangustttinio commented on js/create-data/create-card.js
> +    const newAds = ads;
понял, что совершенно не нужно, убрал

2022-08-11 19:26 UTC, o-bender requested changes

2022-08-11 19:26 UTC, o-bender commented on js/create-data/create-card.js
> +    featuresArray.forEach((element) => {
Как я показывал на консультации тут фрагмент в принципе не нужен. Потому что функция должна только создавать и возвращать элемент card. А пример с append это на будущее.

2022-08-11 19:26 UTC, o-bender commented on js/create-data/create-card.js
> +const renderPopup = (array) => {
Давай сделаем примерно как я показывал на созвоне:
```
const createFeatureElement = (featureName) => {
  // создаём и возвращаем dom элемент feature
};

const createFeatureElements = (features) => features.map(createFeatureElement);

const createPopupElement = (ads) => {
  const cardNode = cardTemplate.cloneNode(true);
  // код заполнения элементов cardNode
  return cardNode;
};

const renderPopup = (popup) => {
  mapCanvas.appendChild(popup);
};
```
Если что я выложил на яндекс диск консультацию, в дискорде в закреплённых есть ссылка на него. Так что там можно подсмотреть детали реализации.

2022-08-11 19:26 UTC, o-bender commented on js/create-data/create-card.js
> +    const pDescription = document.createElement('p');
Да не парься:) Ты же учишься, ты затем сюда и пришёл, что бы в спокойной обстановке разбираться что да как. И если я задаю вопрос это не руководство к действию. Это только вопрос. И да, скорей всего он наводящий, но это моя работа: направлять, предлагать варианты и указывать на возможные проблемы. Как писать код и как проектировать твоё приложение решать только тебе.

2022-08-12 09:57 UTC, o-bender commented
Закрываю т.к. есть новый [PR](https://github.com/htmlacademy-javascript/1801005-keksobooking-26/pull/6) в котором все ошибки учтены.

2022-08-12 09:57 UTC, closed without merging